### ISSUE TITLE
do the printer has glass between lcd? and did u remove it?

### ISSUE THREAD

**Issue by 0x410c** [BleakyTex/Anycubic-PW0-Converter#1]
great work!

i am plannig to buy the printer specifically for pcb exposure, did u remove the glass if there is any? also do u recommend anything else?

**Comment by BleakyTex** [comment]
Thanks!
I did not modify my Anycubic Photon Mono 4, the glass and protective LCD film are in place. 23-25 seconds is enough to expose the noname dry film photoresist from Aliexpress and 0.1-0.12mm resolution (two traces between SOIC pads) is achievable.
